### ISSUE TITLE
Unhandled Exception: System.ArgumentNullException: Value cannot be null.

### ISSUE THREAD

**Issue by silent** [sphexator/Discord.me-bump-bot#1]
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: implementationInstance
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddSingleton[TService](IServiceCollection services, TService implementationInstance)
   at BumpBot.Program.ConfigureServices() in C:\Users\silent\Desktop\Discord.me-bump-bot\BumpBot\Program.cs:line 52
   at BumpBot.Program.BumpBot() in C:\Users\silent\Desktop\Discord.me-bump-bot\BumpBot\Program.cs:line 27
   at BumpBot.Program.Main() in C:\Users\silent\Desktop\Discord.me-bump-bot\BumpBot\Program.cs:line 22

Got this while running it. Any ideas?

In terms of the configuration, how do you choose which server you want to bump? Does it just do the ones your account is connected to Discord.me automatically or do you have to specify within the config?

Also, why doesn't this just support a discord token vs username/password?

**Comment by sphexator** [comment]
Hello

This is currently a WIP project, quite a bit is already put in place, but its not in a functional state at this very moment.

Currently it doesn't fetch server ids automatically from your dashboard, but that might be something I'll implement, it might drain the amount of captcha solves one have though, else the ones you specify in the config. The server field in the config is an array where you add all the servers you wish to bump from your dashboard. How you get the server id for the server is through the element inspector whenever you're on your dashboard, as discord.me uses internal server ids, that's the only way to get the id. 

As this is a bot which is ran in a automated browser, the reason I have username/pass instead of a token is due to oauth login requirement on discord.me in-order to be able to login and access the dashboard. There's a profile path as well which is a way to let the automated browser use your current chrome profile which can inherent your login session.

**Comment by silent** [comment]
Ah okay, thanks for the update as this makes more sense. I'll be following this project :)
